import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import{fileURLToPath}from'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url)),manifest=JSON.parse(fs.readFileSync(path.join(dir,'release-manifest.json'))),origin=process.argv[2]||'https://download.cyb-math.cn';
for(const r of manifest.releases)r.source=path.join(process.env.CYB_RELEASE_ROOT || path.resolve(dir,'../../../outputs'),r.fileName);
const checks=[];
for(const [lang,title] of [['zh-Hans','下载中心'],['zh-Hant','下載中心'],['en','Downloads']]){let r=await fetch(origin+'/?lang='+lang),s=await r.text();assert.equal(r.status,200);assert.ok(s.includes(title));assert.equal((s.match(/class="release-card/g)||[]).length,4);for(const release of manifest.releases)assert.ok(s.includes(release.sha256));checks.push('page '+lang)}
for(const [headers,lang] of [[{Cookie:'cyb-language=en'},'en'],[{'Accept-Language':'zh-Hant'},'zh-Hant'],[{Cookie:'cyb-language=%invalid','Accept-Language':'en'},'en']]){const r=await fetch(origin+'/',{headers});assert.equal(r.status,200);assert.equal(r.headers.get('content-language'),lang)}checks.push('cookie and browser locale including malformed cookie');
assert.deepEqual(await(await fetch(origin+'/health')).json(),{ok:true,releaseDate:manifest.date,files:4});
for(const r of manifest.releases){const url=origin+'/files/'+r.fileName,head=await fetch(url,{method:'HEAD'});assert.equal(head.status,200);assert.equal(+head.headers.get('content-length'),r.bytes);assert.equal(head.headers.get('etag'),'"sha256-'+r.sha256+'"');const response=await fetch(url);assert.equal(response.status,200);const digest=crypto.createHash('sha256');for await(const chunk of response.body)digest.update(chunk);assert.equal(digest.digest('hex').toUpperCase(),r.sha256);checks.push('full file '+r.id)}
const r=manifest.releases[0],start=16777216-6,end=start+20,resp=await fetch(origin+'/files/'+r.fileName,{headers:{Range:`bytes=${start}-${end}`}});assert.equal(resp.status,206);assert.equal(resp.headers.get('content-range'),`bytes ${start}-${end}/${r.bytes}`);assert.deepEqual(Buffer.from(await resp.arrayBuffer()),fs.readFileSync(r.source).subarray(start,end+1));checks.push('range across chunk boundary');
assert.equal((await fetch(origin+'/files/'+r.fileName,{headers:{Range:'bytes=999999999999-'}})).status,416);assert.equal((await fetch(origin+'/__chunks/android/000.part')).status,404);assert.equal((await fetch(origin+'/files/missing.exe')).status,404);checks.push('range and route protection');
const report={passed:true,origin,testedAt:new Date().toISOString(),checks};fs.writeFileSync(path.join(dir,origin.includes('127.0.0.1')?'download-local-test.json':'download-live-test.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
