import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
const directory = path.resolve('.toolchain/harmony/java');
if (/^c:/i.test(directory)) throw new Error('Install portable Java on D: only');
fs.mkdirSync(directory, { recursive: true });
const source = 'https://corretto.aws/downloads/';
const name = 'amazon-corretto-17-x64-linux-jdk.tar.gz';
const checksumResponse = await fetch(`${source}latest_sha256/${name}`, { signal: AbortSignal.timeout(30000) });
if (!checksumResponse.ok) throw new Error('Java checksum unavailable');
const checksum = (await checksumResponse.text()).trim().split(/\s+/)[0];
if (!/^[a-f0-9]{64}$/.test(checksum)) throw new Error('Unexpected Java checksum');
const file = path.join(directory, name);
const response = await fetch(`${source}latest/${name}`, { signal: AbortSignal.timeout(300000) });
if (!response.ok) throw new Error(`Java download HTTP ${response.status}`);
if (!response.url.startsWith(source)) throw new Error('Unexpected Java package source');
await pipeline(Readable.fromWeb(response.body), fs.createWriteStream(file));
const hash = createHash('sha256'); await pipeline(fs.createReadStream(file), hash);
if (hash.digest('hex') !== checksum) throw new Error('Java checksum mismatch');
console.log(JSON.stringify({ file, verified: true, sha256: checksum }));
